{{- $w := .Values.workers.beat -}}
{{- if $w.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $w.name }}
  labels:
    app.kubernetes.io/name: {{ $w.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- include "wcp-workers.commonLabels" . | nindent 4 }}
spec:
  replicas: {{ $w.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $w.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    {{- toYaml $w.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $w.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- include "wcp-workers.commonLabels" . | nindent 8 }}
    spec:
      {{- include "wcp-workers.podSpec" (dict "ctx" . "w" $w) | nindent 6 }}
{{- end }}
