{{- if .Values.mlflow.enabled -}}
{{- $m := .Values.mlflow -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $m.name }}
  labels:
    app.kubernetes.io/name: {{ $m.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- include "wcp-workers.commonLabels" . | nindent 4 }}
spec:
  type: {{ $m.service.type }}
  ports:
    - port: {{ $m.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ $m.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
