"""phase3_business_tables — users, OAuth, payments, subscriptions, and the
M5/M6 social/track-record tables (9 tables total).

Revision ID: 0003_phase3_business_tables
Revises: 0002_phase2_ml_tables
Create Date: 2026-05-02 19:03:23

Adds the Phase-3 business schema:

    - users / user_oauth         : identity + third-party bindings.
    - payments / subscriptions   : transaction log + access-window state.
    - prediction_results         : per-match settlement scorecards.
    - track_record_stats         : public-scoreboard aggregates.
    - share_links / share_cards  : referral attribution + pre-rendered cards.
    - user_favorites             : user ↔ match watch-list.

Generated via ``alembic revision --autogenerate``; only the header was
edited post-generation to use the project's sequential revision id.
``gen_random_uuid()`` is available in PostgreSQL 13+ without enabling any
extension, so no pre-step is required.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0003_phase3_business_tables"
down_revision: Union[str, None] = "0002_phase2_ml_tables"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_cards',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('card_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('width', sa.SmallInteger(), nullable=False),
    sa.Column('height', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cards_platform', 'share_cards', ['platform'], unique=False)
    op.create_index('idx_cards_target', 'share_cards', ['card_type', 'target_id'], unique=False)
    op.create_table('track_record_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stat_type', sa.String(length=30), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('total_predictions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('hits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('hit_rate', sa.Numeric(precision=5, scale=4), server_default='0', nullable=False),
    sa.Column('total_pnl_units', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('roi', sa.Numeric(precision=6, scale=4), server_default='0', nullable=False),
    sa.Column('current_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('best_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stat_type', 'period', name='uq_track_stats_type_period')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('subscription_tier', sa.String(length=20), server_default='free', nullable=False),
    sa.Column('subscription_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locale', sa.String(length=10), server_default='zh-CN', nullable=False),
    sa.Column('timezone', sa.String(length=50), server_default='Asia/Shanghai', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='user', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_subscription', 'users', ['subscription_tier'], unique=False)
    op.create_index('uq_users_email', 'users', ['email'], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_index('uq_users_phone', 'users', ['phone'], unique=True, postgresql_where=sa.text('phone IS NOT NULL'))
    op.create_index('uq_users_uuid', 'users', ['uuid'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('order_no', sa.String(length=64), nullable=False),
    sa.Column('payment_channel', sa.String(length=20), nullable=False),
    sa.Column('amount_cny', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('channel_trade_no', sa.String(length=100), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('callback_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no', name='uq_payments_order_no')
    )
    op.create_index('idx_payments_status', 'payments', ['status'], unique=False)
    op.create_index('idx_payments_user', 'payments', ['user_id'], unique=False)
    op.create_table('share_links',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('short_code', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('utm_source', sa.String(length=50), nullable=True),
    sa.Column('utm_medium', sa.String(length=50), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('click_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('register_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('subscribe_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_code', name='uq_share_links_short_code')
    )
    op.create_index('idx_share_target', 'share_links', ['target_type', 'target_id'], unique=False)
    op.create_index('idx_share_user', 'share_links', ['user_id'], unique=False)
    op.create_table('user_oauth',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_user_id', sa.String(length=200), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_user_oauth_provider_remote')
    )
    op.create_index('idx_oauth_user', 'user_oauth', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('plan_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('price_cny', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('payment_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_subscriptions_expires', 'subscriptions', ['expires_at'], unique=False)
    op.create_index('idx_subscriptions_user', 'subscriptions', ['user_id', 'status'], unique=False)
    op.create_table('user_favorites',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'match_id', name='uq_user_favorites_user_match')
    )
    op.create_table('prediction_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('actual_home_score', sa.SmallInteger(), nullable=False),
    sa.Column('actual_away_score', sa.SmallInteger(), nullable=False),
    sa.Column('result_1x2_hit', sa.Boolean(), nullable=False),
    sa.Column('result_score_hit', sa.Boolean(), nullable=False),
    sa.Column('result_ou25_hit', sa.Boolean(), nullable=True),
    sa.Column('result_btts_hit', sa.Boolean(), nullable=True),
    sa.Column('best_ev_outcome', sa.String(length=30), nullable=True),
    sa.Column('best_ev_odds', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('best_ev_hit', sa.Boolean(), nullable=True),
    sa.Column('pnl_unit', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_id', name='uq_prediction_results_prediction')
    )
    op.create_index('idx_results_match', 'prediction_results', ['match_id'], unique=False)
    op.create_index('idx_results_settled', 'prediction_results', [sa.literal_column('settled_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_results_settled', table_name='prediction_results')
    op.drop_index('idx_results_match', table_name='prediction_results')
    op.drop_table('prediction_results')
    op.drop_table('user_favorites')
    op.drop_index('idx_subscriptions_user', table_name='subscriptions')
    op.drop_index('idx_subscriptions_expires', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('idx_oauth_user', table_name='user_oauth')
    op.drop_table('user_oauth')
    op.drop_index('idx_share_user', table_name='share_links')
    op.drop_index('idx_share_target', table_name='share_links')
    op.drop_table('share_links')
    op.drop_index('idx_payments_user', table_name='payments')
    op.drop_index('idx_payments_status', table_name='payments')
    op.drop_table('payments')
    op.drop_index('uq_users_uuid', table_name='users')
    op.drop_index('uq_users_phone', table_name='users', postgresql_where=sa.text('phone IS NOT NULL'))
    op.drop_index('uq_users_email', table_name='users', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_index('idx_users_subscription', table_name='users')
    op.drop_table('users')
    op.drop_table('track_record_stats')
    op.drop_index('idx_cards_target', table_name='share_cards')
    op.drop_index('idx_cards_platform', table_name='share_cards')
    op.drop_table('share_cards')
    # ### end Alembic commands ###
